AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  DigiLab SAM template for Mandelbrot image generation
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
  Function:
    Architectures:
      - arm64
    Timeout: 60

Resources:
  MandelbrotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "A lambda that generates an image from the Mandelbrot Set."
      PackageType: Image
      Events:
        Mandelbrot:
          Type: Api
          Properties:
            Path: /mandelbrot
            Method: post
      MemorySize: 128
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/mandelbrot
      DockerTag: python3.9-v1

Outputs:
  MandelbrotApi:
    Description: "API Gateway endpoint URL for Mandelbrot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mandelbrot"
